services:
  - type: web
    name: y-sim
    runtime: node
    plan: free
    autoDeploy: false
    buildCommand: npm install
    startCommand: node dist/index.js
     env:
      - key: NODE_VERSION
        value: 18.17.0